version: '3.8'

services:
  mosquitto-broker:
    container_name: mosquitto-broker-app
    build: ./mqtt-broker
    restart: unless-stopped
    ports: 
      - "1883:1883"
    networks:
      - mqtt-internal-network

  paho-client:
    container_name: paho-client-app
    build: ./mqtt-client
    restart: unless-stopped
    volumes:
      - "C:\\Users\\levyg\\Documents\\MEGA\\Repositories\\SEII-LevyGabriel\\IoT\\mqtt-client:/app"
    networks:
      - mqtt-internal-network
      - socket-internal-network
    environment:
      - PYTHONUNBUFFERED=1

  socket-server:
    container_name: socket-server-app
    build: ./socket-server
    restart: unless-stopped
    volumes:
      - "C:\\Users\\levyg\\Documents\\MEGA\\Repositories\\SEII-LevyGabriel\\IoT\\socket-server:/app"
    networks:
      - socket-internal-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  mqtt-internal-network:
    driver: bridge
  socket-internal-network:
    driver: bridge