version: '3.8'

services:
  mosquitto-broker:
    container_name: mosquitto-broker-app
    build: ./broker
    restart: always
    ports: 
      - "1883:1883"
    networks:
      - mqtt-internal-network

  flask-webserver:
    container_name: flask-webserver-app
    build: ./webserver
    restart: always
    depends_on:
      - mosquitto-broker
    volumes: # dev option
      - "C:\\Users\\levyg\\Documents\\MEGA\\Repositories\\SEII-LevyGabriel\\IoT\\webserver:/app"
    ports:
      - "5000:5000"
    networks:
      - mqtt-internal-network
    environment:
      - PYTHONUNBUFFERED=1

  

networks:
  mqtt-internal-network:
    driver: bridge